[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
# serialization
log = "0.4.0"

powdr = { git = "https://github.com/powdr-labs/powdr", branch = "continuations-data-input" }
backend = { git = "https://github.com/powdr-labs/powdr", branch = "continuations-data-input", package = "backend" }
models = { git = "https://github.com/eigmax/powdr_revm", branch = "continuations", package = "models" }
hex = "0.4.3"
thiserror = "1.0"
revm = { git = "https://github.com/powdr-labs/revm", branch = "serde-no-std", default-features = false, features = [ "serde" ] }
serde_json = "1.0.108"

[dev-dependencies]
env_logger = "0.10"
